### ISSUE TITLE
[Bug]DDNSTO验证反复重定向

### ISSUE THREAD

**Issue by daybreak1929** [uiliugang/external-link-auto-redirect#1]
这个网址( https://sttaoyop.ddnsto.com/cgi-bin/luci/ )会无法验证通过，感觉是跳转后直接触发了重定向
但验证通过后的该网站( https://www.ddnsto.com/app/mobile/#/login?url=https://sttaoyop.ddnsto.com/cgi-bin/luci/
)不会自动跳转，总体感觉下来就是关键词白名单触发不及时

除了上述问题，我感觉确实可以给脚本加一个站点单独的开关，不然真不好排查

**Comment by uiliugang** [comment]
前段时间写毕业论文，比较忙，没注意看。
目前来看，通用的方案适配所用情形似乎行不通，下一版本，脚本只会在特定网站启用，适配日常使用的一些网站。

**Comment by uiliugang** [comment]
排除问题网站的方式也可以，添加一个自定义配置导入导出的功能，我周末考虑一下怎么改

**Comment by daybreak1929** [comment]
其他问题我有发在greasyfork的评论区，大佬改完可以测试看看XD
